# fly.toml app configuration file generated for muddy-tree-1008 on 2023-06-14T19:56:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-tree-1008"
primary_region = "iad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
