# fly.toml app configuration file generated for broken-fog-8748 on 2023-06-15T18:21:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-fog-8748"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
